apiVersion: apps/v1
kind: Deployment
metadata:
  name: meteojson2
spec:
  replicas: 3
  selector:
    matchLabels:
      app: meteojson2
  template:
    metadata:
      labels:
        app: meteojson2
    spec:
      containers:
        - name: meteojson2
          image: meteojson2
          ports:
            - containerPort: 8080
