apiVersion: v1
kind: Service
metadata:
  name: meteojson1
spec:
  type: NodePort
  selector:
    app: meteojson1
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30027
